export const letters = [
  { id:'botanist', name:'The Botanist', sender:'Elowen Moss', tone:'#778066', ink:'#263e2e', seal:'#334c38', mark:'❧', note:'pressed fern', salutation:'Dear Keeper of Small Wonders,', body:["The moonwort has flowered three nights early, and every moth in the western garden has gathered to watch.","I found your brass key beneath its roots. Come before dawn, and bring the little green bottle—the one that hums when it rains."], sign:'Ever among the leaves, Elowen' },
  { id:'midnight', name:'Midnight Correspondence', sender:'The Night Clerk', tone:'#303642', ink:'#d8d1bc', seal:'#18233b', mark:'☾', note:'silvered vellum', salutation:'To the One Still Awake,', body:["At thirteen minutes past midnight, the northern bell rang without a hand upon its rope.","Your name appeared in the watch ledger soon after. If this is your doing, kindly leave a candle in the east window. If it is not, leave two."], sign:'The Night Clerk' },
  { id:'crimson', name:'The Crimson Invitation', sender:'Lady Veyra', tone:'#743c34', ink:'#261816', seal:'#681f24', mark:'✦', note:'black-edged', salutation:'Most Discreet Guest,', body:["A chair has been kept for you at Thursday’s impossible supper. Formal dress is admired; alibis are essential.","Present this letter to the doorkeeper with the wooden eye. Under no circumstance compliment the peacock."], sign:'With dangerous affection, Lady Veyra' },
  { id:'home', name:'A Letter From Home', sender:'Mara', tone:'#d6bd91', ink:'#453326', seal:'#805039', mark:'⌂', note:'tied with twine', salutation:'My dearest wanderer,', body:["The roof still leaks above your old chair, the kettle still whistles too loudly, and your brother still denies stealing the plum preserves.","In other words, home waits exactly as you left it. Come back when the road is finished with you."], sign:'All my love, Mara' },
  { id:'archivist', name:'The Archivist', sender:'Orrin Vale', tone:'#aa9472', ink:'#342c25', seal:'#665345', mark:'№', note:'catalogued 7B', salutation:'Regarding Object 7B,', body:["The item you donated is not, as claimed, an ordinary paperweight. It has moved between locked cases on four occasions.","Yesterday it asked after you by name. The archive would appreciate an explanation, preferably before it learns to open doors."], sign:'Orrin Vale, Third Archivist' },
  { id:'alchemist', name:'The Alchemist', sender:'Sable Quince', tone:'#b18a4e', ink:'#44301d', seal:'#8a572e', mark:'△', note:'copper dust', salutation:'Promising Apprentice,', body:["Your tincture has become sentient. This is usually considered a mistake, though its manners are excellent.","I have placed it beside the blue furnace with a saucer of rainwater. Please collect it before it begins negotiating wages."], sign:'Experimentally yours, Sable' },
  { id:'winter', name:'The Winter Letter', sender:'Ilyan Frost', tone:'#8e9ca3', ink:'#29383e', seal:'#667986', mark:'❄', note:'silver thread', salutation:'From beyond the white pass,', body:["Snow has covered the observatory, but the great lens remains warm. Through it we saw a summer sky—and you standing beneath it.","When the first frost reaches your window, draw a circle upon the glass. We will be watching from the other side."], sign:'Ilyan Frost' },
  { id:'rose', name:'The Rose Letter', sender:'Cecily Rook', tone:'#b78382', ink:'#4c292c', seal:'#71333d', mark:'❀', note:'rose-scented', salutation:'Dear Heart,', body:["The rose you left in my book has refused to wither. Its thorns rearrange themselves nightly into tiny words.","Tonight they spelled your name. Tomorrow, perhaps, they will be less polite about your absence."], sign:'Impatiently, Cecily' },
  { id:'unknown', name:'Unknown Sender', sender:'Unknown', tone:'#59473a', ink:'#d2c2a1', seal:'#1d1a18', mark:'?', note:'seal already cracked', salutation:'You do not know me.', body:["That is the safest thing about our acquaintance.","At noon tomorrow, the clockmaker will sell a watch that runs backward. Buy it. Do not wind it until you have forgotten why you wanted it."], sign:'A friend you have not met' },
  { id:'golden', name:'The Golden Letter', sender:'Aurelia Wren', tone:'#ded1ad', ink:'#4d402b', seal:'#c5aa70', mark:'✧', note:'gold-leaf edge', salutation:'To the Patient Correspondent,', body:["Some letters arrive late because they travel a great distance. This one arrived late because it was waiting for the right version of you.","If you are reading now, the little door behind the moon dial has finally opened. Whatever you find there has been yours all along."], sign:'In golden light, Aurelia Wren' }
];